### ISSUE TITLE
engineer build error 

### ISSUE THREAD

**Issue by bretonio** [tylerbutler/engineer#102]
`engineer build` throws an error the gist of which is: `jinja2.exceptions.UndefinedError: engineer.models.PostCollection object has no element 0`.

I also noticed that the `build` command found 0 new or modified posts although I had created one under the `content` directory. O, but let me try to create a new page in `posts`, hang on ...

This was raised [here](https://github.com/tylerbutler/engineer/issues/96) but not addressed.

Okay, so when I add a post under `posts` the build moves forward but balks at processing the 'POST_TIMEZONE`variable in the config file. I have set this to '`America/Sao_Paulo`' following your example and adding my own TZ. So now, 

'expected a timezone name (string) but got <class 'pytz.tzfile.America/Sao_Paulo'> instead`

Looking forward to getting your excellent project working for me.

**Comment by tylerbutler** [comment]
The second issue seems to be caused by a change in the `times` library. The current release version of engineer is quite old and the dev branch has moved from the deprecated times library to Arrow. However, the dev branch has a *lot* of other changes, many of which are not yet documented, so that's probably not a good option.

As a temporary workaround, try explicitly installing times v0.6.2. You can do that with this command:

```
pip install times==0.6.2
```

That at least made the build succeed in my test cases. I just made a change to pin the version of the dependency to 0.6.2 explicitly in the engineer setup, but I don't have time to publish a new version to PyPI. The workaround I mentioned should address it for you in the meantime.

**Comment by bretonio** [comment]
installed times as suggested. No joy! Installed dev distribution as
instructed in docs. Joy! Thank you for your attention to my issue.

cb
